theme: jekyll-theme-minimal
title: Welcome to Dean Patel's personal website!
locale: en_US

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Dean Patel
  avatar: DP_Logo.png
  bio: "This is a sample Jekyll academic website."
  email: patel.dea@northeastern.edu
  # Do not include the @ symbol in your Twitter username
  twitter: DeanP40330856
  linkedin: #dp2
  github: deanpatel2
